### ISSUE TITLE
在IOS上通过设置whistle代理的方式登陆京东APP出现问题

### ISSUE THREAD

**Issue by stayStrong007** [lzwme/ql-scripts#1]
拜读了大佬的教程，跟着试了试，发现：
在手机端设置好代理，那么在登陆京东APP时无法通过“手机验证码登陆”，只能通过“手机号快捷登陆”或者“微信登陆”，即使通过后两种方式成功登陆，查看青龙面板内发现也没有自动更新ck

**Comment by renxia** [comment]
访问一下农场、签到等页面，才会有ck可以提取到

**Comment by stayStrong007** [comment]
> 访问一下农场、签到等页面，才会有ck可以提取到

操作成功，谢谢大佬。但是实验几天发现通过这种方式获取的ck有个特征——以“app_open”开头，且有效期极短，只有几个小时。

**Comment by renxia** [comment]
应该是你同时跑的号太多了。
我试过最开始只跑一个号时有效期有一个星期，后来任务跑多了就会被风控，有效期会超短，多跑几个号后，现在基本是24小时。
还好京东支持添加多个账号，每天都切换一下就可以了。

另外wsck转换应该会久一些，具体我没试过多账号的转换
