### ISSUE TITLE
运行喜马拉雅签到脚本报错

### ISSUE THREAD

**Issue by bserho** [lzwme/ql-scripts#3]
## 开始执行... 2024-07-30 01:19:09

/ql/scripts/raw_main_ql_xmlySign.ts:15
const $= new Env('喜马拉雅签到', { sep: ['\n', '@'] });
         ^
TypeError: utils_1.Env is not a constructor
    at Object.<anonymous> (/ql/scripts/raw_main_ql_xmlySign.ts:15:10)

**Comment by renxia** [comment]
不支持订阅单个脚本文件
