### ISSUE TITLE
拉库失败

### ISSUE THREAD

**Issue by zjk2017** [lzwme/ql-scripts#7]
![image](https://github.com/user-attachments/assets/2422df81-4bbc-46f8-8b70-31f8f446b399)
辛苦库主改下 这就是最新拉失败的详细本子
（除了我没人提这问题呢 拉都拉不了 都咋玩的）

**Comment by renxia** [comment]
你是在Windows下跑的青龙吗

**Comment by zjk2017** [comment]
云服务器 linux的。 原来是行结束符LF的问题，学习了 。不通平台“下一行”不一样，还真没注意过。拉库没问题了。
